version: '3'

services:
  traefik:
    image: traefik:1.7.12-alpine
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  node:
    image: node:12.5.0-alpine
    command: >
      sh -c "npm install
      && npm run start
      "
    working_dir: /home/node/app
    ports:
      - "4000:4000"
    labels:
      traefik.frontend.rule: "Host:node.local"
    volumes:
      - ./app:/home/node/app
      - node_modules:/home/node/app/node_modules

  node2:
    image: node:12.5.0-alpine
    command: npm run start
    working_dir: /home/node/app
    depends_on:
      - node
    ports:
      - "4004:4000"
    labels:
      traefik.frontend.rule: "Host:node2.local"
      traefik.frontend.auth.basic.users: "test:$$apr1$$PcLSHB5h$$p/35NmUIT/H7NP58XbvWt0" # user: test, pwd: test
      # note additional symbol "$" makes escaping.
    volumes:
      - ./app:/home/node/app
      - node_modules:/home/node/app/node_modules

volumes:
  node_modules:
